default_velocity_scaling_factor: 0.5  # 50% de velocidad máxima
default_acceleration_scaling_factor: 0.5  # 50% de aceleración máxima

joint_limits:
  magician_joint_1:
    has_position_limits: true
    min_position: -2.356194490192345  # -135°
    max_position: 2.356194490192345   # +135°
    has_velocity_limits: true
    max_velocity: 5.585053606381855   # 320°/s
    has_acceleration_limits: true
    max_acceleration: 10.0  
    has_jerk_limits: false
  
  magician_joint_2:
    has_position_limits: true
    min_position: 0.0
    max_position: 1.4835298641951802  # 85°
    has_velocity_limits: true
    max_velocity: 5.585053606381855   # 320°/s
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_jerk_limits: false
  
  magician_joint_3:
    has_position_limits: true
    min_position: -0.17453292519943295  # -10°
    max_position: 1.6580627893946132    # +95°
    has_velocity_limits: true
    max_velocity: 5.585053606381855     # 320°/s
    has_acceleration_limits: true
    max_acceleration: 10.0
    has_jerk_limits: false